In [140]:
import numpy as np
num = []
dic = {}
ls = []
filename = 'inp_1M.txt'
with open(filename,'r') as f:
    text = f.read().splitlines()
    

for i in text:
    num.append(int(i))
    
numbers = np.sort(num)
for i in range(len(numbers)):
    if i%2 == 0:
        dic.update({numbers[i]:0})
    else:
        dic.update({numbers[i]:1})
        
for key in num:
    ls.append(dic[key])
    
    
print

<function print>

In [151]:
del text[0]

In [152]:
num = []
for i in text:
    num.append(int(i))

In [153]:
numbers = np.sort(num)


In [132]:
dic = {}
for i in range(len(numbers)):
    if i%2 == 0:
        dic.update({numbers[i]:0})
    else:
        dic.update({numbers[i]:1})
        
        

In [57]:
ls = []
for key in num:
    ls.append(dic[key])
    
ls = np.array(ls)

In [50]:
# filename = 'answers3.txt'
# with open(filename,'a') as f:
#     for i in ls:
#         f.write(str(i)+'\n')

In [65]:
ind = np.random.choice(range(input_matrix.shape[0]), size=(5000,), replace=False)
rest2 = np.array([i for i in range(0,ls.shape[0]) if i not in ind])
rest2 = np.array(rest)



    
    

In [66]:
rest

array([ 3,  5,  7,  9, 13, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30,
       32, 35, 43, 45, 53, 54, 55, 57, 66, 71, 72, 82, 85, 89, 90, 91, 92,
       93])

In [67]:
rest2

array([ 3,  5,  7,  9, 13, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30,
       32, 35, 43, 45, 53, 54, 55, 57, 66, 71, 72, 82, 85, 89, 90, 91, 92,
       93])

In [25]:
dic[5]

0

In [68]:
import numpy as np
from sklearn.model_selection import train_test_split

In [82]:
X = ls
X1, X2= train_test_split(X,test_size=0.5, random_state=42)

In [83]:
X1

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1])

In [84]:
X2

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1])

In [87]:
len(X2)

51

In [90]:
arr = np.append(X1,X2)

In [91]:
filename = 'answersme.txt'
with open(filename,'a') as f:
    for i in arr:
        f.write(str(i)+'\n')

In [105]:
sums = 0
dic = {}
for i in numbers:
    sums += i
    if sums<sum(numbers)/2:
        dic.update({i:0})
    else:
        dic.update({i:1})

In [106]:
ls = []
for key in num:
    ls.append(dic[key])

In [107]:
print(sum(numbers))

5038044


In [108]:
filename = 'answers5.txt'
with open(filename,'a') as f:
    for i in ls:
        f.write(str(i)+'\n')

In [109]:
sum([1,3])

4

In [110]:
dic

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 0,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 0,
 40: 0,
 41: 0,
 42: 0,
 43: 0,
 44: 0,
 45: 0,
 46: 0,
 47: 0,
 48: 0,
 49: 0,
 50: 0,
 51: 0,
 52: 0,
 53: 0,
 54: 0,
 55: 0,
 56: 0,
 57: 0,
 58: 0,
 59: 0,
 60: 0,
 61: 0,
 62: 0,
 63: 0,
 64: 0,
 65: 0,
 66: 0,
 67: 0,
 68: 0,
 69: 0,
 70: 0,
 71: 0,
 72: 0,
 73: 0,
 74: 0,
 75: 0,
 76: 0,
 77: 0,
 78: 0,
 79: 0,
 80: 0,
 81: 0,
 82: 0,
 83: 0,
 84: 0,
 85: 0,
 86: 0,
 87: 0,
 88: 0,
 89: 0,
 90: 0,
 91: 0,
 92: 0,
 93: 0,
 94: 0,
 95: 0,
 96: 0,
 97: 0,
 98: 0,
 99: 0,
 100: 0,
 101: 0,
 102: 0,
 103: 0,
 104: 0,
 105: 0,
 106: 0,
 107: 0,
 108: 0,
 109: 0,
 110: 0,
 111: 0,
 112: 0,
 113: 0,
 114: 0,
 115: 0,
 116: 0,
 117: 0,
 118: 0,
 119: 0,
 120: 0,
 121: 0,
 122: 0,
 12

In [111]:
import numpy as np

def split_array_min_distance(arr):
    sorted_arr = np.sort(arr)
    cum_sum = np.cumsum(sorted_arr)
    total_sum = np.sum(sorted_arr)
    min_diff = np.inf
    split_point = None
    
    for i in range(1, len(sorted_arr)):
        diff = abs(cum_sum[i-1] - (total_sum - cum_sum[i-1]))
        if diff < min_diff:
            min_diff = diff
            split_point = i
    
    return sorted_arr[:split_point], sorted_arr[split_point:]



In [112]:
arr1,arr2 = split_array_min_distance(np.array(num))

In [113]:
arr1

array([  0,   0,   0, ..., 708, 708, 708])

In [114]:
arr2

array([  708,   709,   709, ...,   999,   999, 10000])

In [119]:
dic = {}

    

In [154]:
dic = {}
for i in range(len(numbers)):
    if i<len(numbers)/2:
        dic.update({numbers[i]:0})
    else:
        dic.update({numbers[i]:1})
    

In [155]:
dic

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 0,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 0,
 40: 0,
 41: 0,
 42: 0,
 43: 0,
 44: 0,
 45: 0,
 46: 0,
 47: 0,
 48: 0,
 49: 0,
 50: 0,
 51: 0,
 52: 0,
 53: 0,
 54: 0,
 55: 0,
 56: 0,
 57: 0,
 58: 0,
 59: 0,
 60: 0,
 61: 0,
 62: 0,
 63: 0,
 64: 0,
 65: 0,
 66: 0,
 67: 0,
 68: 0,
 69: 0,
 70: 0,
 71: 0,
 72: 0,
 73: 0,
 74: 0,
 75: 0,
 76: 0,
 77: 0,
 78: 0,
 79: 0,
 80: 0,
 81: 0,
 82: 0,
 83: 0,
 84: 0,
 85: 0,
 86: 0,
 87: 0,
 88: 0,
 89: 0,
 90: 0,
 91: 0,
 92: 0,
 93: 0,
 94: 0,
 95: 0,
 96: 0,
 97: 0,
 98: 0,
 99: 0,
 100: 0,
 101: 0,
 102: 0,
 103: 0,
 104: 0,
 105: 0,
 106: 0,
 107: 0,
 108: 0,
 109: 0,
 110: 0,
 111: 0,
 112: 0,
 113: 0,
 114: 0,
 115: 0,
 116: 0,
 117: 0,
 118: 0,
 119: 0,
 120: 0,
 121: 0,
 122: 0,
 12

In [156]:
ls = []
for key in num:
    ls.append(dic[key])
    

In [157]:
filename = 'answers69.txt'
with open(filename,'w') as f:
    for i in num:
        f.write(str(dic[i])+'\n')

In [184]:
import numpy as np
num = []
dic = {}
ls = []
filename = 'inp_1M.txt'
with open(filename,'r') as f:
    text = f.read().splitlines()    

for i in text:
    num.append(int(i))
    
numbers = np.sort(num)

In [185]:

dic = {}
for i in range(len(numbers)):
    if i<len(numbers)/4:
        dic.update({numbers[i]:0})
    else:
        dic.update({numbers[i]:1})
        
# filename = 'answers69ooo.txt'
# with open(filename,'w') as f:
#     f.write('xc\n')
#     for i in num:
#         f.write(str(dic[i])+'\n')  

In [186]:
filename = 'answers666_999.txt'
with open(filename,'w') as f:
    f.write('1000000\n')
    for i in num:
        if i%2==0:
            f.write('1' +'\n')
        else:
            f.write('0'+'\n')